version: '3.6'
services:
  heimdall:
    image: linuxserver/heimdall

    volumes:
      - ${SSD}/docs_heimdall/:/config

    networks:
      - http
      - internet

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Lisbon

    deploy:
      <<: *deploy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.heimdall.rule=Host(`heimdall.${MAIN_DOMAIN}`)" # host
        - "traefik.http.services.heimdall.loadbalancer.server.port=80" # port
        - "traefik.http.routers.heimdall.tls.certresolver=le" # let's encrypt
        - "traefik.http.routers.heimdall.middlewares=auth@file" # authelia
  

networks:
  # internet access
  internet:
    external: true

  # http traffic network
  http:
    external: true
