version: '3.6'
services:
  heimdall:
    image: linuxserver/heimdall

    volumes:
      - ${RAID}/heimdall/:/config

    networks:
      - http
      - internet

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.heimdall.rule=Host(`heimdall.${MAIN_DOMAIN}`)" # host
        - "traefik.http.services.heimdall.loadbalancer.server.port=80" # port
        - "traefik.http.routers.heimdall.tls.certresolver=le" # let's encrypt
        - "traefik.http.routers.heimdall.middlewares=auth@file" # authelia
  

networks:
  # internet access
  internet:
    external: true

  # http traffic network
  http:
    external: true