version: '3.6'

services:
  tdias:
    image: nginx:alpine
      
    networks:
      - http

    volumes:
      - ${SSD}/sites_tdias.tech:/usr/share/nginx/html
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.machine == dockernas
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tdias.rule=Host(`tdias.tech`)" # host
        - "traefik.http.services.tdias.loadbalancer.server.port=80" # port
        - "traefik.http.routers.tdias.tls.certresolver=le" # let's encrypt

networks:
  # internet access
  internet:
    external: true

  # http traffic network
  http:
    external: true
