[api]
  dashboard = true

[providers]
  [providers.docker]
    network = "http"
    exposedByDefault = false
    swarmMode = true
    swarmModeRefreshSeconds = "3s"

  [providers.file]
    filename = "/traefik-providers.toml"

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

[log]
  level = "INFO"

[certificatesResolvers]
  [certificatesResolvers.le.acme]
    email = "tiago@tdias.tech"
    storage = "/data/acme.json" 

    [certificatesResolvers.le.acme.tlsChallenge]
