version: '3.6'

services:
  # portainer agent - installed in all linux machines
  agent:
    image: portainer/agent

    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      AGENT_SECRET: "${PORTAINER_AGENT_SECRET}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

    networks:
      - portainer

    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  # portainer web interface - installed on manager
  portainer:
    image: portainer/portainer
    command: 
      - --tlsskipverify 
      - --no-auth 
      - --no-analytics
      - -H 
      - tcp://tasks.agent:9001 

    volumes:
      - ${SSD}/docker_portainer:/data

    networks:
      - portainer
      - http

    environment:
      AGENT_SECRET: "${PORTAINER_AGENT_SECRET}"

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.machine == dockernas
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${MAIN_DOMAIN}`)" # host
        - "traefik.http.services.portainer.loadbalancer.server.port=9000" # port
        - "traefik.http.routers.portainer.tls.certresolver=le" # let's encrypt
        - "traefik.http.routers.portainer.middlewares=auth@file" # authelia

networks:
  portainer:
    driver: overlay

  # internet access
  internet:
    external: true
    
  # http traffic network
  http:
    external: true
